### PR TITLE
Brianbolt/issue887

### LINKED ISSUE #887: ACAS SSO: Cannot grant roles via group membership
**Steps to Reproduce**
Setup an ACAS server with SSO turned on, an associated Okta App, and some groups in Okta to manage users & admins. Ensure one user has only the "user" role.

Bugs:

1. Unrecognized system roles need to be created manually, rather than being autocreated by ACAS. i.e. My role "System"/"ACAS"/"ROLE_OKTA-APP-ACAS-USER" should get auto-created in ACAS LsRoles if it does not exist. 

2. Instead the adding of that role to login users fails until someone manually adds that role to ACAS.

3. User with one group gets their group mangled (iterates through letters) because ACAS code expects a list
Incoming user with:

```
acas_1       | [ACAS] 2022-03-03T19:17:05.386Z info: "would have logged: login attempt with data: {\"ip\":\"::ffff:127.0.0.1\",\"referer\":\"https://schrodinger.okta.com/\",\"agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15\"} and user: {\"issuer\":\"http://www.okta.com/exkepxk9jsbvQBVtG2p7\",\"sessionIndex\":\"id1646335025053.892152643\",\"nameID\":\"brian.bolt@schrodinger.com\",\"nameIDFormat\":\"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress\",\"email\":\"brian.bolt@schrodinger.com\",\"firstName\":\"Brian\",\"lastName\":\"Bolt\",\"group\":\"okta-app-compbio-acas-user\",\"attributes\":{\"email\":\"brian.bolt@schrodinger.com\",\"firstName\":\"Brian\",\"lastName\":\"Bolt\",\"group\":\"okta-app-compbio-acas-user\"}}" 
gets parsed to this:
acas_1       | [ACAS] 2022-03-03T19:17:05.400Z info: [{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_O"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_K"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_T"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_A"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_-"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_A"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_P"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_P"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_-"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_C"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_O"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_M"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_P"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_B"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_I"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_O"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_-"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_A"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_C"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_A"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_S"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_-"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_U"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_S"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_E"},{"lsType":"System","lsKind":"ACAS","roleName":"ROLE_R"}] 
```

Buggy code is this in CustomerSpecificServerFunctions.coffee:
```
getSystemRolesFromSSOProfile = (profile) =>
        roles = []
        for group in profile.group
                roleName = group.toUpperCase()
                lsKind = 'ACAS'
                if roleName.indexOf("CMPDREG") > -1
                        lsKind = 'CmpdReg'
                roles.push
                        lsType: 'System'
                        lsKind: lsKind
                        roleName: "ROLE_#{roleName}"
        return roles 
```

should check whether profile.group is a list or a string before iterating through it.

### PR DESCRIPTION
**Pull request by brianbolt**
Fixes #887

Tested:

- New user creation
- New role creation + user role syncing
- Email change
- First name and last name change
- Revoking user from groups

### CODE REVIEW

File: modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee [hunk 1]
```diff
@@ -40,10 +40,10 @@ exports.promisifyRequestResponseStatus = (fun, args) ->
 	# Custom promisify function to convert "json, status" type callback
 	# functions where status > 400 is an error to a standard err, response
 	# promise return
-	fun[util.promisify.custom] = (args) =>
+	fun[util.promisify.custom] = (...args) =>
```
Comment (brianbolt) [inline modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee:43]: This function essentially takes our standard ACAS proxy routes which use the function callback signature "json, status" and turns it into a promise.  It makes code that uses these functions much easier.  Previously this function didn't support signatures that had more than one argument like the setupRoutesInternal function added in this commit.

File: modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee [hunk 2]
```diff
@@ -40,10 +40,10 @@ exports.promisifyRequestResponseStatus = (fun, args) ->
...
 		new Promise((resolve, reject) =>
-			fun args, (json, status) =>
-				if status >= 400
+			fun ...args, (json, status) =>
+				if typeof status != 'number' || status >= 400
```
Comment (brianbolt) [inline modules/ServerAPI/src/server/routes/ServerUtilityFunctions.coffee:46]: Better checking that return status code from http request is a number.

File: modules/ServerAPI/src/server/routes/SetupRoutes.coffee [hunk 3]
```diff
@@ -1,27 +1,23 @@
 exports.setupRoutes = (app, loginRoutes) ->
 	app.post '/api/setup/:typeOrKind', exports.setupTypeOrKind
 
-exports.setupTypeOrKind = (req, resp) ->
+exports.setupTypeOrKindInternal = (typeOrKind, roles, callback) ->
```
Comment (brianbolt) [inline modules/ServerAPI/src/server/routes/SetupRoutes.coffee:4]: These changes are to make setupTypeOrKind a useable function within node rather than just a request. I verified that the setup routes still work by editing a ConfJSON.coffee file and making sure new items get loaded to the database properly.

File: modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee [hunk 4]
```diff
@@ -234,15 +244,25 @@ exports.ssoLoginStrategy = (req, profile, callback) ->
 
 	if config.all.server.security.saml.roles.sync
 		console.log "Checking for roles to sync"
-		# Check the users ldap roles against the saved roles
+
+		# Get the groups from the profile and put them into ACAS format [{roleName: , lsType: 'System', lsKind: }]
 		ssoSystemRoles = getSystemRolesFromSSOProfile(profile)
+		console.log("Found #{ssoSystemRoles.length} 'ACAS'/'CRREG' roles in sso profile for author #{savedAuthor.userName}, #{JSON.stringify(ssoSystemRoles)}")
```
Comment (bffrost) [inline modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee:250]: nit: We actually just check for `CMPDREG` and then assume any groups aside from that are ACAS-related even if they don't have `'ACAS'`. At minimum I would correct `CRREG` to `CMPDREG` in this logging line.

**Review by bffrost — CHANGES_REQUESTED** [review]
Mostly looks great. Really appreciate the added comments and logging. Noted a few areas I'd like to see small changes, then this will be ready.

File: modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee (hunk 4 above)
Comment (brianbolt) [reply modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee:250]: I went with the minimum here. I added notes to the function to explain what we are doing.

File: modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee [hunk 5]
```diff
@@ -146,22 +146,29 @@ exports.findByUsername = (username, fn) ->
...
-	for group in profile.group
-		roleName = group.toUpperCase()
-		lsKind = 'ACAS'
-		if roleName.indexOf("CMPDREG") > -1
-			lsKind = 'CmpdReg'
-		roles.push
-			lsType: 'System'
-			lsKind: lsKind
-			roleName: "ROLE_#{roleName}"
+	if profile.group?
```
[the remark this answers is not in the document]
Comment (brianbolt) [reply modules/ServerAPI/src/server/CustomerSpecificServerFunctions.coffee:149]: That's a good idea, I just added this.

**Comment by bffrost** [comment]
@brianbolt I don't see a new commit yet with that new config. Maybe you forgot to push?

**Comment by brianbolt** [comment]
@bffrost Yes, didn't push, it's there now along with the other changes I made.

**Review by bffrost — APPROVED** [review]
LGTM!
